{% set version = '1.1.13' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-polspline
  version: {{ version|replace("-", "_") }}

source:
  fn: polspline_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/polspline_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/polspline/polspline_{{ version }}.tar.gz
  sha256: 937561842d754e40a48d2e6d0c49638739e3fdc9bb81e9d8d05adea828371f22

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('polspline')"           # [not win]
    - "\"%R%\" -e \"library('polspline')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=polspline
  license: GPL (>= 2)
  summary: Routines for the polynomial spline fitting routines hazard regression, hazard estimation
    with flexible tails, logspline, lspec, polyclass, and polymars, by C. Kooperberg
    and co-authors.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
