# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "da9CTtVrcX+kfSfdee+F4s2RGK92VGAvL8QefrN7LcEEyLXU9tx9fUlZ50j9rO+EMyBswUX4xMdudQlzaZtrr7S8kKCUdnSV3+56Vn0JaRqC9ExaHFMaaHmCKEI2erojO1srUfvBVM3ZNLL7VhAUQeXOtfpqj7OfQrjXDiFjvM7VPOQwJUD9mE1WLlgeXg5ajXR1zZrabONCqIJMRU/VJ1OsCWqxB3b6KHRP4YR+7Xp5l0T+zCOJZ2WLpjlddFym1VDWACc8oUVkwENC4poqpQWO+ucvsB7EJadtdIa4WF2Vy4OMk15nGw6/L/Zlb2ENFlRovvsc5b7J8cIh/KJuntwFg1pkJxiWkijgxEtht7geXQdSlmmiiadTopyvx+dwZw8NbFuou/WvdRXqWxWUGXPyR61rw54iuO0EARJ/QgtpSZ2l46sO2WwsMhM9S/JTzgpeD9SEsxoGMTtWakcqGyPmEAYFi0NsbRx/CXBQwMZycA15A6iSqCyFkocpEW0ZaN1qH2q+zR/iUPAYQowYqW+Fa2Z+IuHJHJFSrPfoexpWOFk+VraIo7FblkkGA/Zt+cziYqh3ceN/LKySVCwQ0r9KCyhtNOV9gkN/rwV/vdluy3MuPR/EgAKpE6d4Ay0LrUXSImYrpA3F4/SDzZ85jt+EazSqfKacsab83cS+vO0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml