travis:
  secure:
    BINSTAR_TOKEN: da9CTtVrcX+kfSfdee+F4s2RGK92VGAvL8QefrN7LcEEyLXU9tx9fUlZ50j9rO+EMyBswUX4xMdudQlzaZtrr7S8kKCUdnSV3+56Vn0JaRqC9ExaHFMaaHmCKEI2erojO1srUfvBVM3ZNLL7VhAUQeXOtfpqj7OfQrjXDiFjvM7VPOQwJUD9mE1WLlgeXg5ajXR1zZrabONCqIJMRU/VJ1OsCWqxB3b6KHRP4YR+7Xp5l0T+zCOJZ2WLpjlddFym1VDWACc8oUVkwENC4poqpQWO+ucvsB7EJadtdIa4WF2Vy4OMk15nGw6/L/Zlb2ENFlRovvsc5b7J8cIh/KJuntwFg1pkJxiWkijgxEtht7geXQdSlmmiiadTopyvx+dwZw8NbFuou/WvdRXqWxWUGXPyR61rw54iuO0EARJ/QgtpSZ2l46sO2WwsMhM9S/JTzgpeD9SEsxoGMTtWakcqGyPmEAYFi0NsbRx/CXBQwMZycA15A6iSqCyFkocpEW0ZaN1qH2q+zR/iUPAYQowYqW+Fa2Z+IuHJHJFSrPfoexpWOFk+VraIo7FblkkGA/Zt+cziYqh3ceN/LKySVCwQ0r9KCyhtNOV9gkN/rwV/vdluy3MuPR/EgAKpE6d4Ay0LrUXSImYrpA3F4/SDzZ85jt+EazSqfKacsab83cS+vO0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
